{{- if and (eq .Values.replication.role "primary") .Values.initSQL.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db
  namespace: {{ .Values.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  configmap.sql: |
{{ .Values.initSQL.script | indent 4 }}
{{- end }}
