{{- if eq .Values.replication.role "primary" }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}

---
apiVersion: v1
kind: Secret
metadata:
  name: streaming-replication-secret
  namespace: {{ .Values.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.replicationConfig.user }}
  password: {{ .Values.replicationConfig.password }}

---
{{- if .Values.minioIntegration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: {{ .Values.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.minioIntegration.credentials.accessKey }}
  SECRET_ACCESS_KEY: {{ .Values.minioIntegration.credentials.secretKey }}
{{- end }}

---
{{- end }}
{{- if eq .Values.replication.role "replica" }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}
{{- end }}
