{{- if and .Values.serviceExport.enabled .Values.clusters.cluster1.enabled }}
{{- range .Values.serviceExport.services }}
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec: {}
{{- end }}
{{- end }}
